enemy_color: "blue"
# enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----工业相机参数-----#####
camera_name: "mindvision"
exposure_ms: 8
gamma: 0.6
vid_pid: "f622:d132"

#####-----USB相机参数-----#####
image_width: 640
image_height: 360
new_image_width: 1280
new_image_height: 720
fov_h: 87.7
fov_v: 56.7 
new_fov_h: 67
new_fov_v: 40.9
usb_frame_rate: 100
usb_exposure: 315 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96


#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x411
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

com_port: "/dev/gimbal"

#####-----tracker参数-----###
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 150

#####-----aimer参数-----#####
yaw_offset: 0 # degree -2.5 注意下面全是角度
pitch_offset: 3.5 # degree 2
comming_angle: 70 # degree
leaving_angle: 20 # degree
min_spin_speed: 2 # rad/s
decision_speed: 12 # rad/s
high_speed_delay_time: 0.4 # s
low_speed_delay_time: 0.4 # s

#####-----decider参数-----#####
mode: 2

#####-----shooter参数-----#####
first_tolerance: 2 # 近距离射击容差，degree
second_tolerance: 0.8 # 远距离射击容差，degree
judge_distance: 0.5 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.0537px
camera_matrix: [1547.0332457776835, 0, 616.14141111864421, 0, 1546.9942054775638, 526.07959560278164, 0, 0, 1]
distort_coeffs: [-0.10904280974514378, 0.20002327508248774, -0.0013946058213655597, 0.00073153454042437424, 0]


# 相机同理想情况的偏角: yaw0.51 pitch0.36 roll-1.49 degree
# 标定板到世界坐标系原点的水平距离: 1.28 m
# 标定板同竖直摆放时的偏角: yaw13.86 pitch14.47 roll-0.92 degree
R_camera2gimbal: [-0.0090356068460771717, 0.0059764874322568084, 0.99994131798165786, -0.9996208310529261, -0.026065194328919017, -0.0088769234340009186, 0.026010611949366897, -0.99964237967513547, 0.0062097361821325621]
t_camera2gimbal: [0.00052620816886527562, -0.0066404749315596943, -0.049418770899485591]
#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.600   # s
predict_time: 0.090     # s